### ISSUE TITLE
Bug in prior variance - may affect C++ function?

### ISSUE THREAD

**Issue by RuthHarbord** [schw4b/mdm#3]
I have opened a pull request with this bug corrected from the R function. Can you correct it for the C++ version?

CSt[,,1] = CS0 (replaces Ct[,,1] = CS0)
RSt[,,t] = CSt[,,(t-1)] / delta

(Note the effect on the LPL is likely to be small).

**Comment by schw4b** [comment]
Ruth, alright thank you. I just merged your pull request and applied a few fixes that addressed the renaming of the function. I will fix the bug in the C++ code later, and also rename the function to remove the terminology from filtering to lpl, as you suggested.

**Comment by schw4b** [comment]
Fix also in C++ code
